In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import *

In [5]:
data = [
    [-1,2]
    ,[-0.5,6]
    ,[0,10]
    ,[1,18]
]
X = pd.DataFrame(data).to_numpy()

In [6]:
min = X.min(axis=0)
max = X.max(axis=0)
jicha = max - min

In [7]:
min

array([-1.,  2.])

In [8]:
max

array([ 1., 18.])

In [9]:
jicha

array([ 2., 16.])